// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA48zEzLIHjMau1fOjRkq1T3ROQF6JIKnI',
    appId: '1:1097929083749:web:d646269fc7b87a6eca2f8c',
    messagingSenderId: '1097929083749',
    projectId: 'fleetgo-c76c3',
    authDomain: 'fleetgo-c76c3.firebaseapp.com',
    storageBucket: 'fleetgo-c76c3.firebasestorage.app',
    measurementId: 'G-7W87ZGVRH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiv1_aJ_AD1LsoKjtuYHp6bFj36dWewug',
    appId: '1:1097929083749:android:34b6d6f9c48a3b8bca2f8c',
    messagingSenderId: '1097929083749',
    projectId: 'fleetgo-c76c3',
    storageBucket: 'fleetgo-c76c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj962mmhF4VD6XusyFB2PpyOIq8Vq3j1o',
    appId: '1:1097929083749:ios:8e6682c362db1a16ca2f8c',
    messagingSenderId: '1097929083749',
    projectId: 'fleetgo-c76c3',
    storageBucket: 'fleetgo-c76c3.firebasestorage.app',
    androidClientId: '1097929083749-hfevtcmp5chr4si1d9n50qo1me305p45.apps.googleusercontent.com',
    iosClientId: '1097929083749-mpqkql72ukg248f1sastdlui389b672b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fleetgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj962mmhF4VD6XusyFB2PpyOIq8Vq3j1o',
    appId: '1:1097929083749:ios:8e6682c362db1a16ca2f8c',
    messagingSenderId: '1097929083749',
    projectId: 'fleetgo-c76c3',
    storageBucket: 'fleetgo-c76c3.firebasestorage.app',
    androidClientId: '1097929083749-hfevtcmp5chr4si1d9n50qo1me305p45.apps.googleusercontent.com',
    iosClientId: '1097929083749-mpqkql72ukg248f1sastdlui389b672b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fleetgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA48zEzLIHjMau1fOjRkq1T3ROQF6JIKnI',
    appId: '1:1097929083749:web:df9fd9a8c56da666ca2f8c',
    messagingSenderId: '1097929083749',
    projectId: 'fleetgo-c76c3',
    authDomain: 'fleetgo-c76c3.firebaseapp.com',
    storageBucket: 'fleetgo-c76c3.firebasestorage.app',
    measurementId: 'G-LXF6GZ0T8W',
  );
}
